name: "Frigate (Hikvision Mod)"
version: "0.16.4-1"
slug: "frigate_hikvision"
description: "Frigate NVR 0.16 with Position-Based ONVIF Fix for Hikvision."
url: "https://github.com/omarmeleis/frigate-hikvision"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
image: "ghcr.io/omarmeleis/frigate-hikvision"
ingress: true
ingress_port: 5000
panel_icon: mdi:cctv
full_access: true
ports:
  5000/tcp: 5000
  8554/tcp: 8554
  8555/tcp: 8555
  8555/udp: 8555
map:
  - addon_config:rw
  - media:rw
devices:
  - /dev/dri:/dev/dri
  - /dev/dma_heap:/dev/dma_heap
  - /dev/bus/usb:/dev/bus/usb
options: {}
schema: {}
