name: "Frigate (Hikvision Mod)"
version: "0.16.4-5"
slug: "frigate_hikvision"
description: "Frigate NVR with Position-Based ONVIF"
url: "https://github.com/blakeblackshear/frigate"
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
ingress: true
ingress_port: 5000
panel_icon: mdi:cctv
ports:
  5000/tcp: 5000
  8554/tcp: 8554
  8555/tcp: 8555
  8555/udp: 8555
map:
  - addon_config:rw
  - media:rw
options: {}
schema: {}
