name: "Frigate (Hikvision Mod)"
version: "0.16.4-4"
slug: "frigate_hikvision"
description: "Frigate NVR with Position-Based ONVIF"
url: "https://github.com/blakeblackshear/frigate"
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
ingress: true
ingress_port: 5000      # <--- The Critical Fix (Tells UI where to look)
panel_icon: mdi:cctv
ports:
  5000/tcp: 5000        # <--- Standard Web Port
  8554/tcp: 8554        # <--- Standard RTSP Port
  8555/tcp: 8555        # <--- Standard WebRTC Port
  8555/udp: 8555        # <--- Standard WebRTC Port
map:
  - config:rw
  - media:rw
options: {}
schema: {}
