name: "Frigate (Hikvision Mod)"
version: "0.16.0-hik1"
slug: "frigate_hikvision"
description: "Frigate NVR 0.16 with Position-Based ONVIF Fix for Hikvision."
url: "https://github.com/omarmeleis/frigate-hikvision"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
image: "ghcr.io/omarmeleis/frigate-hikvision"
ingress: true
ingress_port: 5000
panel_icon: mdi:cctv
full_access: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_PTRACE
  - SYS_NICE
  - DAC_READ_SEARCH
map:
  - addon_config:rw
  - media:rw
  - share:rw
options: {}
schema: {}
